### ISSUE TITLE
 'Factory2D' object has no attribute 'CreateLine'

### ISSUE THREAD

**Issue by lampt2010** [evereux/pycatia-drawing-template#1]
I downloaded the project and run with env python 3.8 and pycatia 0.5.4 , I got the error when run function create_border(sheet, size_info) with catia V5 R20 
The detail in  **return **Line2D(self.factory_2d.CreateLine(i_x1,** i_y1, i_x2, i_y2))** and error  **'Factory2D' object has no attribute 'CreateLine'**

**Comment by evereux** [comment]
Can you post the full traceback for me please including showing how you executed the script.

I'm going to update the minimum requirements to be (but I'm not convinced that this is the problem here though, I'm going to test your versions shortly).
* python >= 3.9
* pycatia >= 0.5.7

**Comment by evereux** [comment]
It doesn't work for me in python 3.8 and pycatia 0.5.7. So you're going to need to upgrade. Sorry for the inconvenience.

**Comment by lampt2010** [comment]
Thanks for reply me. Below is the traceback 

```
Traceback (most recent call last):
  File "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\lampt\PycharmProjects\pythonProject\pycatia-drawing-template\main.py", line 62, in <module>
    create_border(sheet, size_info)
  File "C:\Users\lampt\PycharmProjects\pythonProject\pycatia-drawing-template\application\border.py", line 24, in create_border
    factory_2d.create_line(0, 0, sheet_x, 0)
  File "C:\Users\lampt\PycharmProjects\pythonProject\pycatia-drawing-template\venv\lib\site-packages\pycatia\sketcher_interfaces\factory_2D.py", line 366, in create_line
    return Line2D(self.factory_2d.CreateLine(i_x1, i_y1, i_x2, i_y2))
AttributeError: 'Factory2D' object has no attribute 'CreateLine'
python-BaseException
```

edited: changed code to triple backquotes for proper formatting

**Comment by lampt2010** [comment]
Hi @evereux 
I have a question, Y can make an example about using drawing dimensions to calculate the distance between 2 points like same as 

```
 Dim MyView As DrawingView
                |      Set MyView = MySheet.Views.ActiveView
                |      Dim Fact2D  As Factory2D
                |      Set Fact2D = MyView.Factory2D
                |      Dim Point1 As Point2D
                |      Dim Point2 As Point2D
                |      Set Point1 = Fact2D.CreatePoint(40, 230)
                |      Set Point2 = Fact2D.CreatePoint(80, 210)
                |      Dim Line1 As Line2D
                |      Set Line1 = Fact2D.CreateLine(50, 10, 150, 10)
                |      Dim iType As catDimType
                |      iType = catDimDistance
                |      Dim myElements(1)
                |      myElements(1) = Array(Point1,Point2)
                |      Dim selpoints(3)
                |      selpoints(3) = Array(0, 0, 0, 0)
                |      Dim MyDimension As DrawingDimension
                |      Set MyDimension = MyView.Dimensions.Add2(iType, myElements(1), selpoints(3), Line1, 0)

```

This is an example from the class DrawingDimensions in pycatia . I think the code cannot work properly because the MyView.Dimensions.Add2(iType, myElements(1), selpoints(3), Line1, 0) did not run on catia v5

edited: changed code to triple backquotes for proper formatting

**Comment by evereux** [comment]
When posting multi-line code samples please wrap text in triple back quotes instead of single. I have edited your posts to do this.

With regards to your original issue: Have you updated your python and pycatia versions as suggested above and re-run the script?

> Y can make an example about using drawing dimensions to calculate the distance between 2 points ... 

Questions regarding pycatia itself should be posted to the pycatia github repository as this is not the place for that. The text you have copied was taken from the V5Automation.chm document and is provided for reference only and is not directly related to the usage of pycatia as it relates to the original CATScript/VBA examples. It isn't valid python code. When asking your question please provide the example script you are trying to run (stripped down including only code related to your question) and what the expected result is. Reading what you have provided so far I think it's worth you going through a number of the examples provided to get a better idea of how pycatia works.

**Comment by lampt2010** [comment]
Sorry about my question ,
i read your code and  edited 
`
def get_background_view_and_factory(sheet: DrawingSheet) :

    views = sheet.views
    main_view = DrawingView( views.get_item_by_name('Main View'))
    background_view = DrawingView(views.get_item_by_name('Background View').com_object)
    background_view.activate()
    factory_2d =Factory2D(background_view.factory_2d.com_object)

    return background_view, factory_2d, main_view
`
Instead of factory2d = background_view.factory_2d . I edited to factory_2d =Factory2D(background_view.factory_2d.com_object) and its work for me 
I think in pycatia document explaines the class Factory2d receives a com object

**Comment by evereux** [comment]
closing issue as resolved
